### ISSUE TITLE
Request for Inclusion in Puzzle Hunt Toolbox

### ISSUE THREAD

**Issue by SAMFYB** [svisser/crossword#2]
Hi,

I'm collecting tools that might help solving puzzle hunt problems, here -> [puzzle-hunter-toolbox](https://github.com/SAMFYB/puzzle-hunter-toolbox).

Would you mind if I include this project in the list and link to here?

Thanks!
Sam

**Comment by svisser** [comment]
@SAMFYB Hi there, thanks for your interest! Yeah, that's fine.

It's been a while since I worked on this project but hopefully it's useful!

Best,
Simeon

**Comment by SAMFYB** [comment]
@svisser Thank you!
